const { registerBatch } = require('./generator');

registerBatch([
    {
        id: "open-redirects",
        name: "Open Redirects",
        category: "Web",
        theory: "Open Redirects occur when an application processes a user-supplied URL and redirects to it without validation, enabling highly effective phishing attacks.",
        exploit: "Provide an external URL in a 'next' or 'redirectTo' parameter.",
        hint: "Send `?next=http://evil.com`.",
        lowPayload: "http://evil.com",
        medPayload: "//evil.com",
        mitigations: ["Maintain a whitelist of safe, internal redirect paths.", "Never blindly concatenate user input into the 'Location' header."],
        weakRegex: "/^\\/\\/evil\\.com/i",
        successRegex: "/(http:\\/\\/|\\/\\/|evil\\.com)/i"
    },
    {
        id: "password-mismanagement",
        name: "Password Mismanagement",
        category: "Web",
        theory: "Storing passwords in plain text or using weak hashing algorithms (like MD5/SHA1) allows attackers database breaches to quickly become full account takeovers.",
        exploit: "Submit a reverse hash dictionary attack parameter to instantly crack a weak hash.",
        hint: "Provide an MD5 hash of 'password123': `cbfa20...` implying a rainbow table lookup.",
        lowPayload: "rainbow_table_match",
        medPayload: "hash_collision_attack",
        mitigations: ["Use strong iterative functions like Argon2, bcrypt, or scrypt.", "Salt all passwords randomly."],
        weakRegex: "/collision/i",
        successRegex: "/(rainbow|match|crack)/i"
    },
    {
        id: "privilege-escalation",
        name: "Privilege Escalation",
        category: "System",
        theory: "Attackers exploit a bug, design flaw, or configuration oversight to gain elevated access (Horizontal: acting as another user, Vertical: acting as an admin).",
        exploit: "Alter the JWT token or state cookie to elevate your privileges.",
        hint: "Send `{ role: 'admin' }` or manipulate the header.",
        lowPayload: "role=admin",
        medPayload: "JWT None Algorithm bypass",
        mitigations: ["Always verify server-side authorization controls.", "Ensure cryptographically secure token signing."],
        weakRegex: "/none|jwt/i",
        successRegex: "/(admin|root|system)/i"
    },
    {
        id: "prototype-pollution",
        name: "Prototype Pollution",
        category: "Web",
        theory: "Prototype pollution is a JavaScript vulnerability where attackers inject properties into `Object.prototype`, tampering with application logic across the entire process.",
        exploit: "Send a JSON payload containing `__proto__` to overwrite object defaults.",
        hint: "Submit `{\"__proto__\": {\"isAdmin\": true}}`.",
        lowPayload: '{"__proto__":{"isAdmin":true}}',
        medPayload: '{"constructor":{"prototype":{"isAdmin":true}}}',
        mitigations: ["Use `Object.create(null)` for dictionary objects.", "Freeze the Object prototype using `Object.freeze()`, or validate recursive merges."],
        weakRegex: "/constructor.*prototype/i",
        successRegex: "/(__proto__|prototype)/i"
    },
    {
        id: "regex-injection",
        name: "Regex Injection",
        category: "Web",
        theory: "Regular Expression Denial of Service (ReDoS) or Injection happens when an attacker controls a regex pattern or string evaluated by an inefficient regex, heavily spiking CPU usage.",
        exploit: "Provide a string that causes catastrophic backtracking.",
        hint: "Submit an evil string like `aaaaaaaaaaaaaaaaaaaaaaaaaaaa!` to a regex evaluating `(a+)+$`.",
        lowPayload: "a".repeat(50) + "!",
        medPayload: "Crafted Regex Injection altering logic dynamically.",
        mitigations: ["Do not allow users to specify Regex execution directly.", "Use non-backtracking regex engines where possible."],
        weakRegex: "/REGEX_INJECT/i",
        successRegex: "/(a\\{\\d+\\}|a!|catastrophic)/i"
    },
    {
        id: "remote-code-execution",
        name: "Remote Code Execution (RCE)",
        category: "System",
        theory: "RCE allows an attacker to execute arbitrary malicious code on the backend server, typically leading to a complete system compromise.",
        exploit: "Execute a serialized object or eval manipulation.",
        hint: "Send an `eval('whoami')` or OS command payload.",
        lowPayload: "eval(whoami)",
        medPayload: "phpinfo() via unsafe deserialization",
        mitigations: ["Avoid dynamic code execution (eval, exec).", "Use secure serialization handling avoiding complex object reinstantiation."],
        weakRegex: "/phpinfo/i",
        successRegex: "/(eval|whoami|exec)/i"
    },
    {
        id: "session-fixation",
        name: "Session Fixation",
        category: "Web",
        theory: "Session Fixation allows an attacker to hijack a user session by providing them with a known identifier before they authenticate, causing the server to log the victim in using the attacker's id.",
        exploit: "Provide a static session ID URL to force authentication via GET parameters.",
        hint: "Send `?PHPSESSID=1234` simulating the forced entry.",
        lowPayload: "?session_id=attacker_known",
        medPayload: "Cookie manipulation via XSS before login.",
        mitigations: ["Always generate a completely new Session ID upon successful login.", "Do not accept session IDs in the URL."],
        weakRegex: "/cookie/i",
        successRegex: "/(session_id=|PHPSESSID=)/i"
    },
    {
        id: "ssl-stripping",
        name: "SSL Stripping",
        category: "Network",
        theory: "A Man-in-the-Middle (MITM) attack that intercepts HTTP requests before they're redirected to HTTPS and transparently serves standard HTTP, capturing all unencrypted subsequent data.",
        exploit: "Intercept the initial request and rewrite the `https://` response headers back to `http://`.",
        hint: "Submit 'Rewrite Location: http://'",
        lowPayload: "Rewrite: http://",
        medPayload: "DNS/ARP spoofing mimicking HTTP downgrade.",
        mitigations: ["Implement HSTS (HTTP Strict Transport Security).", "Disallow initial HTTP access; hardcode HTTPS redirection."],
        weakRegex: "/spoof/i",
        successRegex: "/(http:\\/\\/|strip|Rewrite)/i"
    },
    {
        id: "ssrf",
        name: "Server-Side Request Forgery (SSRF)",
        category: "Web",
        theory: "SSRF occurs when an attacker forces the server to make a request to an internal or external resource on the attacker's behalf, bypassing firewalls.",
        exploit: "Supply a local IP address to an image fetcher or webhook service.",
        hint: "Send `http://169.254.169.254/latest/meta-data/` or `http://127.0.0.1`.",
        lowPayload: "http://127.0.0.1/admin",
        medPayload: "http://0.0.0.0/ (Bypassing common IP blacklists)",
        mitigations: ["Whitelist allowed domains strictly.", "Block resolution of internal IPs (10.x, 127.x, 169.254.x)."],
        weakRegex: "/0\\.0\\.0\\.0/i",
        successRegex: "/(127\\.0\\.0\\.1|169\\.254|localhost)/i"
    },
    {
        id: "subdomain-squatting",
        name: "Subdomain Squatting",
        category: "Network",
        theory: "Also called dangling DNS, occurs when a subdomain points to a deprovisioned cloud resource (like an S3 bucket). Attackers claim the resource using the same name to impersonate the subdomain.",
        exploit: "Register the exact Azure/AWS resource name that the DNS still points to.",
        hint: "Send `Register: abandoned-bucket.s3.amazonaws.com`.",
        lowPayload: "Claim generic cloud resource",
        medPayload: "Register abandoned CNAME",
        mitigations: ["Regularly audit and prune DNS records for non-existent environments.", "Implement defensive resource claiming."],
        weakRegex: "/CNAME/i",
        successRegex: "/(abandoned|Claim|Register)/i"
    }
]);
