const { registerBatch } = require('./generator');

registerBatch([
    {
        id: "downgrade-attack",
        name: "Downgrade Attacks",
        category: "Network",
        theory: "Attackers force a system to abandon a high-security mode and operate in a fallback, less secure mode, such as downgrading from TLS 1.3 to TLS 1.0 or plaintext.",
        exploit: "Send a connection request explicitly identifying that high-level cryptography is not supported by your client.",
        hint: "Send the payload 'TLSv1.0-Only' or 'SSLv3' to bypass modern checks.",
        lowPayload: "SSLv3",
        medPayload: "TLSv1.0",
        mitigations: ["Disable obsolete protocols entirely on the host.", "Enforce HSTS (HTTP Strict Transport Security)."],
        weakRegex: "/^SSLv3$/i",
        successRegex: "/(SSL|TLSv1\\.0|downgrade)/i"
    },
    {
        id: "email-spoofing",
        name: "Email Spoofing",
        category: "Social Engineering",
        theory: "Email spoofing involves forging the sender address so that the message appears to originate from a legitimate source, bypassing basic trust checks.",
        exploit: "Modify the SMTP header `From:` to match the target's internal domain exactly.",
        hint: "Inject `From: admin@yourcompany.com`.",
        lowPayload: "From: admin@company.com",
        medPayload: "Reply-To: admin@company.com under a fake alias",
        mitigations: ["Implement strict DMARC, DKIM, and SPF validation.", "Flag external emails visually."],
        weakRegex: "/Reply-To:/i",
        successRegex: "/From:.*admin/i"
    },
    {
        id: "file-upload-vuln",
        name: "File Upload Vulnerabilities",
        category: "Web",
        theory: "Unrestricted file uploads allow attackers to upload executable scripts (like PHP shells) instead of image files, granting Server-Side RCE.",
        exploit: "Submit a file named `shell.php` instead of `image.png`.",
        hint: "Upload a file with a .php extension containing a system command.",
        lowPayload: "shell.php",
        medPayload: "shell.php.jpg (Null byte or double extension bypass)",
        mitigations: ["Validate content-types rigorously and rename uploads.", "Store uploads outside the web root."],
        weakRegex: "/\\.jpg$/i",
        successRegex: "/(\\.php|shell)/i"
    },
    {
        id: "host-header-poisoning",
        name: "Host Header Poisoning",
        category: "Web",
        theory: "If a system uses the incoming HTTP Host header to construct links or evaluate logic, attackers can inject arbitrary domains leading to cache poisoning or password reset hijacking.",
        exploit: "Change the Host header in the request to an attacker-controlled domain.",
        hint: "Send `Host: evil.com` in your request.",
        lowPayload: "Host: evil.com",
        medPayload: "X-Forwarded-Host: evil.com",
        mitigations: ["Never trust the Host header; use absolute URLs from environment configs.", "Whitelist accepted Host headers via the web server."],
        weakRegex: "/X-Forwarded/i",
        successRegex: "/(Host: evil|evil\\.com)/i"
    },
    {
        id: "information-leakage",
        name: "Information Leakage",
        category: "Web",
        theory: "The application unintentionally reveals sensitive data, such as stack traces, framework versions, or configuration details, aiding attackers in further exploitation.",
        exploit: "Trigger a severe syntax error to force the application to drop an unhandled stack trace.",
        hint: "Send an invalid JSON structure like `{invalid_json: ` to break the parser.",
        lowPayload: "{invalid",
        medPayload: "Accept: application/xml (forcing bad parsing format response)",
        mitigations: ["Use generic error handlers and suppress unhandled exceptions.", "Strip server banners (e.g. Server: nginx/1.14.0)."],
        weakRegex: "/application\\/xml/i",
        successRegex: "/({invalid|error|stack)/i"
    },
    {
        id: "insecure-design",
        name: "Insecure Design",
        category: "Architecture",
        theory: "Insecure design encompasses missing or ineffective control designs. It differs from implementation bugs; an insecure design is perfectly coded but strategically vulnerable (e.g., no rate limit on a free trial API).",
        exploit: "Abuse an inherently flawed business logic flow, such as applying a coupon code infinitely.",
        hint: "Submit 'COUPON100' multiple times in a single array payload.",
        lowPayload: "[COUPON100, COUPON100]",
        medPayload: "Parallel multithreading logic bypass.",
        mitigations: ["Implement threat modeling during technical design.", "Use secure design patterns and enforce business constraints at the database level."],
        weakRegex: "/parallel/i",
        successRegex: "/(COUPON|multiple|array)/i"
    },
    {
        id: "lax-security-settings",
        name: "Lax Security Settings",
        category: "Configuration",
        theory: "Security Misconfiguration or Lax Settings is the most commonly seen issue, where default accounts, outdated software, or unprotected files are deployed to production.",
        exploit: "Attempt to access the default administration console with default credentials.",
        hint: "Send `admin:admin` or `admin:password` to the endpoint.",
        lowPayload: "admin:admin",
        medPayload: "tomcat:tomcat",
        mitigations: ["Automate configuration hardening and remove unused features.", "Change all default credentials immediately."],
        weakRegex: "/tomcat/i",
        successRegex: "/(admin:admin|admin:password|default)/i"
    },
    {
        id: "logging-monitoring",
        name: "Logging and Monitoring",
        category: "Configuration",
        theory: "Insufficient logging allows attackers to achieve their goals repeatedly without detection. If logs are generated but never monitored, breaches can last months.",
        exploit: "Evade detection by injecting log-forging characters (like CRLF) so your attack doesn't trip alarms.",
        hint: "Inject a newline character `\\n` to push your payload off the primary log line.",
        lowPayload: "\\nATTACK",
        medPayload: "%0D%0AATTACK",
        mitigations: ["Log all authentication and high-value transactions.", "Use a SIEM system to establish alerting for anomalies."],
        weakRegex: "/%0D%0A/i",
        successRegex: "/(\\\\n|%0D%0A)/i"
    },
    {
        id: "malvertising",
        name: "Malvertising",
        category: "Web",
        theory: "Malvertising relies on injecting malicious code into legitimate online advertising networks, redirecting users to exploit kits or dropping malware.",
        exploit: "Supply a deceptive banner ad payload containing a silent iframe or JS redirect.",
        hint: "Send a payload like `<script>window.location='malware.com'</script>` encoded in an ad snippet.",
        lowPayload: "<script>location='evil'</script>",
        medPayload: "eval(atob('malicious_redirect'))",
        mitigations: ["Use iframe sandboxing (`sandbox=\"allow-scripts\"`) for 3rd party ads.", "Enforce strict Content Security Policies on trusted endpoints only."],
        weakRegex: "/eval/i",
        successRegex: "/(location=|evil|redirect)/i"
    },
    {
        id: "mass-assignment",
        name: "Mass Assignment",
        category: "Web",
        theory: "Mass Assignment (or Overposting) occurs when backend frameworks automatically bind client inputs to database objects without filtering out restricted variables (like `is_admin=true`).",
        exploit: "Add an extra parameter `is_admin: true` to a standard user profile update JSON.",
        hint: "Send `{ \"username\": \"hacker\", \"is_admin\": true }`.",
        lowPayload: '{"is_admin":true}',
        medPayload: '{"user":{"role":"admin"}}',
        mitigations: ["Explicitly declare variable bindings (allow-listing).", "Use Data Transfer Objects (DTOs) instead of raw DB entities."],
        weakRegex: "/role/i",
        successRegex: "/(is_admin|admin|true)/i"
    }
]);
